dev-exam-master/config/routes.rb
Rails.application.routes.draw do
  resources :rental_properties
end

dev-exam-master/app/models/desired_condition.rb
class DesiredCondition < ApplicationRecord
  belongs_to :rental_property, optional: true
end

dev-exam-master/app/models/rental_property.rb
class RentalProperty < ApplicationRecord
 has_many :desired_conditions, dependent: :destroy
 accepts_nested_attributes_for :desired_conditions, allow_destroy: true
end

dev-exam-master/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

dev-exam-master/app/controllers/rental_properties_controller.rb
class RentalPropertiesController < ApplicationController
  before_action :set_rental_property, only: [:show, :edit, :update, :destroy]

  def index
    @rental_properties = RentalProperty.all
  end

  def new
    5.times do
    @rental_property = RentalProperty.new
    @rental_property.desired_conditions.build
    end
  end

  def show
  end

  def edit
  end

  def create
    @rental_property = RentalProperty.new(rental_property_params)
    @rental_property.desired_conditions.build
      if @rental_property.save
        redirect_to rental_properties_path
      else
        render :new
      end
  end

  def update
    if @rental_property.update(rental_property_params)
      redirect_to rental_properties_path
    else
      render :edit
    end
  end

  def destroy
    @rental_property.destroy
      redirect_to rental_properties_url
  end

  private

  def set_rental_property
    @rental_property = RentalProperty.find(params[:id])
  end

  def rental_property_params
    params.require(:rental_property).permit(:property_name, :rent, :street_address, :house_age, :remarks, desired_conditions_attributes: [:id, :route_name, :station_name, :walking_minutes])
  end
end

dev-exam-master/app/helpers/rental_properties_helper.rb
module RentalPropertiesHelper
end

dev-exam-master/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DevExam</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

dev-exam-master/app/views/rental_properties/_form.html.erb
<% 5.times do%>
<%= form_for(@rental_property) do |f| %>
  <% if rental_property.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(rental_property.errors.count, "error") %> prohibited this rental_property from being saved:</h2>
      <ul>
      <% rental_property.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :物件名 %>
    <%= f.text_field :property_name %>
  </div>

  <div class="field">
    <%= f.label :賃料 %>
    <%= f.number_field :rent %>円
  </div>

  <div class="field">
    <%= f.label :住所 %>
    <%= f.text_field :street_address %>
  </div>

  <div class="field">
    <%= f.label :築年数 %>
    <%= f.text_field :house_age %>年
  </div>

  <div class="field">
    <%= f.label :備考 %>
    <%= f.text_area :remarks %>
  </div>

<hr/>
<%= f.fields_for :desired_conditions do |desired_condition_form| %>

  <h3>最寄り駅１</h3>

  <div class="field">
    <%= desired_condition_form.label :roote_name, "路線名" %>
    <%= desired_condition_form.text_field :roote_name %>
  </div>

  <div class="field">
    <%= desired_condition_form.label :station_name, "駅名" %>
    <%= desired_condition_form.text_field :station_name %>
  </div>

  <div class="field">
    <%= desired_condition_form.label :walking_minutes, "徒歩分数" %>
    <%= desired_condition_form.text_field :walking_minutes %>
  </div>

  <h3>最寄り駅2</h3>

  <div class="field">
    <%= desired_condition_form.label :roote_name, "路線名" %>
    <%= desired_condition_form.text_field :roote_name %>
  </div>

  <div class="field">
    <%= desired_condition_form.label :station_name, "駅名" %>
    <%= desired_condition_form.text_field :station_name %>
  </div>

  <div class="field">
    <%= desired_condition_form.label :walking_minutes, "徒歩分数" %>
    <%= desired_condition_form.text_field :walking_minutes %>
  </div>
  <br>


<% end %>


  <div class="actions">
    <%= f.submit %>
  </div>
  
<% end %>
<% end %>

dev-exam-master/app/views/rental_properties/edit.html.erb
<h1>編集</h1>
<br>
<br>
<h1>物件編集</h1>


<%= render 'form', rental_property: @rental_property %>

<%= link_to '詳細', @rental_property %> |
<%= link_to '戻る', rental_properties_path %>

dev-exam-master/app/views/rental_properties/index.html.erb
<h1>一覽</h1>
<hr/>
<br>

<h1>物件一覽</h1>
<br>

<table>
  <thead>
    <tr>
      <th>物件名</th>
      <th>賃料</th>
      <th>住所</th>
      <th>築年数</th>
      <th>備考</th>
    </tr>
  </thead>

  <tbody>
    <% @rental_properties.each do |rental_property| %>
      <tr>
        <td><%= rental_property.property_name %></td>
        <td><%= rental_property.rent %>円</td>
        <td><%= rental_property.street_address %></td>
        <td><%= rental_property.house_age %>年</td>
        <td><%= rental_property.remarks %></td>
        <td><%= link_to '詳細', rental_property %></td>
        <td><%= link_to '編集', edit_rental_property_path(rental_property) %></td>
        <td><%= link_to '削除', rental_property_path(rental_property), method: :delete %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to '物件を登録する', new_rental_property_path %>

dev-exam-master/app/views/rental_properties/new.html.erb
<h1>登録</h1>
<br>
<br>
<h1>物件登録</h1>

<%= render 'form', rental_property: @rental_property %>

<%= link_to '戻る', rental_properties_path %>

dev-exam-master/app/views/rental_properties/show.html.erb
<h1>閲覧</h1>
<br>

<p>
  <strong>物件名:</strong>
  <%= @rental_property.property_name %>
</p>

<p>
  <strong>賃料:</strong>
  <%= @rental_property.rent %>円
</p>

<p>
  <strong>住所:</strong>
  <%= @rental_property.street_address %>
</p>

<p>
  <strong>築年数:</strong>
  <%= @rental_property.house_age %>年
</p>

<p>
  <strong>備考:</strong>
  <%= @rental_property.remarks %>
</p>

<hr/>
<% @rental_property.desired_conditions.each do |desired_condition| %>
<h3>最寄り駅</h3>

<p>
  <strong>路線名:</strong>
  <%= desired_condition.roote_name %>
</p>

<p>
  <strong>駅名:</strong>
 <%= desired_condition.station_name %>
</p>

<p>
  <strong>徒歩分数:</strong>分
 <%= desired_condition.walking_minutes %>
</p>

<% end %>

<%= link_to '編集', edit_rental_property_path(@rental_property) %> |
<%= link_to '戻る', rental_properties_path %>