config/routes.rb
Rails.application.routes.draw do
  get 'users/new'
  resources :sessions, only: [:new, :create, :destroy]
  resources :users
end

app/models/blog.rb
class Blog < ApplicationRecord
  belongs_to :user
  validates :title, presence: true
  validates :content, presence: true
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
    include SessionsHelper
  end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
    before_action :set_blog, only: [:show, :edit, :update,:destroy]
    def index
      @blogs = Blog.all
    end
  
    def show
      @blog = Blog.find(params[:id])
    end
  
    def new
      @blog = Blog.new
    end
  
    def edit
      @blog = Blog.find(params[:id])
    end
  
    def create
      @blog = Blog.new(blog_params)
      if params[:back]
        render :new
      else
        if @blog.save
          redirect_to root_path, notice: "登録完了"
        else
          render :new
        end
      end
    end
  
    def update
      @blog = Blog.find(params[:id])
      @blog.update!(blog_params)
      redirect_to blogs_path, notice: "更新完了"
    end
  
    def destroy
      @blog = Blog.find(params[:id])
      @blog.destroy
      redirect_to blogs_path, notice: "削除完了"
    end
  
    # def confirm
    #   @blog= Blog.new(blog_params)
    #   render :new if @blog.invalid?
    # end
  
    private
  
    def blog_params
      params.require(:blog).permit(:name, :description)
    end
  
    def set_blog
      @blog = Blog.find(params[:id])
    end
  end
  

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id)
    else
      flash[:danger] = 'ログインに失敗しました'
      render 'new'
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:notice] = 'ログアウトしました'
    redirect_to new_session_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update]
  #edit, :update, :destroyの時は ensure_correct_userを呼び出す。別のユーザーが編集できない様にする。
  before_action :ensure_correct_user,{only:[:edit, :update, :destroy]}
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(session[:user_id])
    else
      render 'new'
    end
  end

  def update
    if @user.update(user_params)
      redirect_to user_path, notice: "画像を登録しました"
    else
      render 'edit'
    end
  end

  def edit
  end

  def show
  end
#ユーザidとログイン中のユーザーが異なる場合、権限がありませんとnoticeに出力させる
  def ensure_correct_user
    if @user.id != current_user.id 
      flash[:notice] = "権限がありません"
      redirect_to pictures_path
    end
  end

  private

#ユーザのパラメータ（:name, :email, :password, :password_confirmation, :user_image, :user_image_cache）を受け取る
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :user_image, :user_image_cache)
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  def logged_in?
    current_user.present?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/blogs/_form.html.erb
<%= form_with(model: @blog, local: true ) do |t| %>
  <% if @blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= @blog.errors.count %>件のエラーがあります。</h2>
      <ul>

      <% @blog.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="blog_title">
    <%= t.label :件名 %><br>
    <%= t.text_field :title %>
  </div>
  <div class="blog_title">
    <%= t.label :内容 %><br>
    <%= t.text_area :content %>
  </div>
  <%= t.submit %>
<% end %>

<%= link_to "一覧画面にもどる", blogs_path %>

app/views/blogs/confirm.html.erb
<h3>以下の内容で、送信する。</h3>

<%= form_with(model: @blog, local: true) do |form| %>
  <%= form.hidden_field :ttile %>
  <%= form.hidden_field :content %>

  <p>タイトル:<%= @blog.title %></p>
  <p>本文:<%= @blog.content %></p>
  <%= form.submit  "登録する" %>

  <%= form.submit "戻る", title: 'back' %>
<% end %>

app/views/blogs/edit.html.erb
<h1>編集</h1>

 <%= render 'form' %>

app/views/blogs/index.html.erb
<h3>全ユーザーの投稿一覧</h3>

<p><%= notice %></p>

<% @blogs.each do |blog| %>

  <div class="one_blog">
    <p class="blog_user"><%= image_tag "man.png", size: '23x23' %><%= blog.user.name %></p>
    <p class="blog_content"><%= blog.content %></p>
    <p><%= image_tag blog.image.to_s %></p>
    <div class="blog_option">
      <p><%= link_to '詳細を見る', blog_path(blog.id) %></p>
      <p><%= link_to "編集する", edit_blog_path(blog.id) %></p>
      <p><%= link_to "削除する", blog_path(blog.id), method: :delete, data: { confirm: '本当に削除しますか？' }  %></p>
    </div>
  </div>
<% end %>

<p class="to_other_page"><%= link_to '新しく投稿する', new_blog_path %></p>

app/views/blogs/new.html.erb
<h1>新規登録</h1>

 <%= render 'form' %>

app/views/blogs/show.html.erb
<h1>ブログ詳細画面</h1>
<p>タイトル: <%= @blog.title %></p>
<p>詳細: <%= @blog.content %></p>

<%= link_to "back", blogs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GithubGroupwork</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "#{key}") %>
    <% end %>

    <% if logged_in? %>
      <%= link_to "Profile", user_path(current_user.id) %>
      <%= link_to "Logout", session_path(current_user.id), method: :delete %>
    <% else %>
      <%= link_to "Sign up", new_user_path %>
      <%= link_to "Login", new_session_path %>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/users/edit.html.erb
<h1>プロフィール画像設定</h1>

<%= form_with(model: @user, local: true) do |form| %>
  <br>
    <%= form.file_field :user_image %>
    <%= form.hidden_field :user_image_cache%>
    <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

<%= link_to "マイページへ", user_path(current_user) %>

app/views/users/new.html.erb
<div class="main-container ">
<h1>新規登録</h1>

<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this @user from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_with(model: @user, local: true) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :email %> 
  <%= f.email_field :email %>

  <%= f.label :user_image %>
  <%= f.file_field :user_image %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>

  <%= f.submit "Create my account" %>
<% end %>
</div>

app/views/users/show.html.erb
<p>メールアドレス: <%= @user.email %></p>

<div class="show_image">
  <%= image_tag @user.user_image.url if @user.user_image.url %>
</div>

<% unless @user.id != current_user.id %>
<%= link_to "プロフィール画像設定", edit_user_path %>
<% end %>
<%= link_to "お気に入り一覧へ", favorites_path %>
<%= link_to "投稿一覧画面へ", pictures_path %>
<%= link_to "投稿する", new_picture_path %>